// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxRn37SuReGQBI7n8uvV_AOI1TIIP0G6U',
    appId: '1:843515707465:web:7bf3c3a85f59d6ce11bf98',
    messagingSenderId: '843515707465',
    projectId: 'bus-tracking-application-86342',
    authDomain: 'bus-tracking-application-86342.firebaseapp.com',
    storageBucket: 'bus-tracking-application-86342.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAby_lX512-dbdFmjKlCiO9htE5sTGp9D4',
    appId: '1:843515707465:android:a22c7e016c7ce22a11bf98',
    messagingSenderId: '843515707465',
    projectId: 'bus-tracking-application-86342',
    storageBucket: 'bus-tracking-application-86342.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnC0nkrjaVBcUXlerhYVqZGg4Pkxy3erA',
    appId: '1:843515707465:ios:b106f29fa321305b11bf98',
    messagingSenderId: '843515707465',
    projectId: 'bus-tracking-application-86342',
    storageBucket: 'bus-tracking-application-86342.appspot.com',
    iosClientId: '843515707465-vpvm4jktv0qm32uult03unk0t43dllhd.apps.googleusercontent.com',
    iosBundleId: 'com.example.collegeBusManagment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnC0nkrjaVBcUXlerhYVqZGg4Pkxy3erA',
    appId: '1:843515707465:ios:b106f29fa321305b11bf98',
    messagingSenderId: '843515707465',
    projectId: 'bus-tracking-application-86342',
    storageBucket: 'bus-tracking-application-86342.appspot.com',
    iosClientId: '843515707465-vpvm4jktv0qm32uult03unk0t43dllhd.apps.googleusercontent.com',
    iosBundleId: 'com.example.collegeBusManagment',
  );
}
